### CONSULTAR UN PRODUCTOS
GET http://127.0.0.1:9000/api/productos/6453e75343185f27fa223cb8 HTTP/1.1

### CONSULTAR TODOS LOS PRODUCTOS


GET http://127.0.0.1:9000/api/productos/ HTTP/1.1

###ENVIAR PRODUCTOS
POST http://127.0.0.1:9000/api/productos HTTP/1.1
Content-Type: application/json

{
    "nombre": "Mesa",
    "descripcion": "Mesa para cuatros",
    "precio": "500.200",
    "stock": "50",
    "tipo": "Hogar",
    "imagen": "https://w7.pngwing.com/pngs/628/169/png-transparent-table-chair-bench-garden-furniture-dining-table-angle-furniture-rectangle-thumbnail.png"
}
### ACTUALIZAR PRODUCTOS
PUT http://127.0.0.1:9000/api/productos/6453e75343185f27fa223cb8 HTTP/1.1
Content-Type: application/json

{
    "nombre": "camisa",
    "descripcion": "Camsia negra de algodon, talla S",
    "precio": "200000",
    "stock": "23",
    "tipo": "ropa",
    "imagen": "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885_1280.jpg"
}

### BORRAR PRODUCTOS
DELETE http://127.0.0.1:9000/api/productos/645db01c482e7df0e52d10f1 HTTP/1.1